name: Deploy Code
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: action/checkout@v4
      - name: Installing Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      # - run: bundle exec rake
      