name: Deploy Code
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Running Test
        run: gem install bundler
        run: bundle install
        run: rails test
      # - run: bundle exec rake
      