name: Deploy Code
# workflow_dispatch is to run manually
on: [push, workflow_dispatch]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Installing Bundler
        run: gem install bundler
      - name: Installing Gems
        run: bundle install
      - name: Running Test
        run: bundle exec rails test
  
  deploy:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Installing Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Installing Bundler
        run: gem install bundler
      - name: Installing Gems
        run: bundle install
      - name: Running Test
        run: echo "Deploying ..."
